services:
  # Checkout Services
  app.strategies.magento.get.guest.items:
    class: AppBundle\Http\ResourceStrategy\Magento\Cart\Items\Guest\GetResource
    arguments:
      - "@app.scope.context"
      - "@app.strategy.generator"
    tags:
      - { name: 'strategies', type: 'magento' }

  app.strategies.magento.post.guest.items:
      class: AppBundle\Http\ResourceStrategy\Magento\Cart\Items\Guest\PostResource
      arguments:
        - "@app.scope.context"
        - "@app.strategy.generator"
      tags:
        - { name: 'strategies', type: 'magento' }

  app.strategies.magento.get.customer.items:
    class: AppBundle\Http\ResourceStrategy\Magento\Cart\Items\Customer\GetResource
    arguments:
      - "@app.scope.context"
      - "@app.strategy.generator"
    tags:
      - { name: 'strategies', type: 'magento' }

  app.strategies.magento.post.customer.items:
    class: AppBundle\Http\ResourceStrategy\Magento\Cart\Items\Customer\PostRequest
    arguments:
      - "@app.scope.context"
      - "@app.strategy.generator"
    tags:
      - { name: 'strategies', type: 'magento' }

  app.strategies.magento.get.customer.customer:
    class: AppBundle\Http\ResourceStrategy\Magento\Customer\GetCustomerResource
    arguments:
      - "@app.scope.context"
      - "@app.strategy.generator"
    tags:
      - { name: 'strategies', type: 'magento' }

  # Checkout Services
  app.strategies.magento.get.checkout.guest.payment:
    class: AppBundle\Http\ResourceStrategy\Magento\Checkout\Guest\GetPaymentResource
    arguments:
      - "@app.scope.context"
      - "@app.strategy.generator"
    tags:
      - { name: 'strategies', type: 'magento' }

  app.strategies.magento.get.checkout.guest.shipping:
    class: AppBundle\Http\ResourceStrategy\Magento\Checkout\Guest\GetShippingMethodsResource
    arguments:
      - "@app.scope.context"
      - "@app.strategy.generator"
    tags:
      - { name: 'strategies', type: 'magento' }

  app.strategies.magento.get.checkout.customer.payment:
    class: AppBundle\Http\ResourceStrategy\Magento\Checkout\Customer\GetPaymentResource
    arguments:
      - "@app.scope.context"
      - "@app.strategy.generator"
    tags:
      - { name: 'strategies', type: 'magento' }

  app.strategies.magento.get.checkout.customer.shipping:
    class: AppBundle\Http\ResourceStrategy\Magento\Checkout\Customer\GetShippingMethodsResource
    arguments:
      - "@app.scope.context"
      - "@app.strategy.generator"
    tags:
      - { name: 'strategies', type: 'magento' }

  app.strategies.magento.get.checkout.customer.totals_information:
    class: AppBundle\Http\ResourceStrategy\Magento\Checkout\Customer\PostTotalsInformation
    arguments:
      - "@app.scope.context"
      - "@app.strategy.generator"
    tags:
      - { name: 'strategies', type: 'magento' }

  # Catalog services
  app.strategies.magento.get.categories:
    class: AppBundle\Http\ResourceStrategy\Magento\Catalog\Categories\GetResource
    arguments:
      - "@app.scope.context"
      - "@app.strategy.generator"
      - "%shop_admin_user%"
      - "%shop_admin_password%"
    tags:
      - { name: 'strategies', type: 'magento' }

  app.strategies.magento.get.categories.list:
    class: AppBundle\Http\ResourceStrategy\Magento\Catalog\Categories\GetListResource
    arguments:
      - "@app.scope.context"
      - "@app.strategy.generator"
      - "%shop_admin_user%"
      - "%shop_admin_password%"
    tags:
      - { name: 'strategies', type: 'magento' }

  app.strategies.magento.get.product:
    class: AppBundle\Http\ResourceStrategy\Magento\Catalog\Product\GetResource
    arguments:
      - "@app.scope.context"
      - "@app.strategy.generator"
      - "%shop_admin_user%"
      - "%shop_admin_password%"
    tags:
      - { name: 'strategies', type: 'magento' }

  app.strategies.magento.get.product.attribute.options:
    class: AppBundle\Http\ResourceStrategy\Magento\Catalog\Product\Attribute\Options\GetResource
    arguments:
      - "@app.scope.context"
      - "@app.strategy.generator"
      - "%shop_admin_user%"
      - "%shop_admin_password%"
    tags:
      - { name: 'strategies', type: 'magento' }

  app.strategies.magento.get.product.attribute:
    class: AppBundle\Http\ResourceStrategy\Magento\Catalog\Product\Attribute\GetResource
    arguments:
      - "@app.scope.context"
      - "@app.strategy.generator"
      - "%shop_admin_user%"
      - "%shop_admin_password%"
    tags:
      - { name: 'strategies', type: 'magento' }

  app.strategies.magento.get.configurable.product.children:
    class: AppBundle\Http\ResourceStrategy\Magento\Catalog\Product\Type\Configurable\GetChildrenResource
    arguments:
      - "@app.scope.context"
      - "@app.strategy.generator"
      - "%shop_admin_user%"
      - "%shop_admin_password%"
    tags:
      - { name: 'strategies', type: 'magento' }

  # Sales Order Services
  app.strategies.magento.get.orders:
    class: AppBundle\Http\ResourceStrategy\Magento\Orders\GetResource
    arguments:
      - "@app.scope.context"
      - "@app.strategy.generator"
      - "%shop_admin_user%"
      - "%shop_admin_password%"
    tags:
      - { name: 'strategies', type: 'magento' }
