services:
  app.controller.catalog:
    class: AppBundle\Controller\CatalogController
    arguments: ["@app.strategy.generator"]
  app.controller.checkout:
    class: AppBundle\Controller\CheckoutController
    arguments: ["@app.strategy.generator"]
  app.controller.api.customer:
    class: AppBundle\Controller\Api\CustomerController
    arguments: ["@app.strategy.generator"]
  app.controller.api.checkout:
    class: AppBundle\Controller\Api\CheckoutController
    arguments: ["@app.strategy.generator"]
